[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
if   = '''! has('kaoriya')'''
hook_post_update = '''
    if dein#util#_is_windows()
        let cmd = 'tools\\update-dll-mingw'
    elseif dein#util#_is_cygwin()
        let cmd = 'make -f make_cygwin.mak'
    elseif executable('gmake')
        let cmd = 'gmake'
    else
        let cmd = 'make'
    endif
    let g:dein#plugin.build = cmd
'''

#[[plugins]]
#repo     = 'Shougo/vimfiler'
#depends  = 'unite.vim'
#hook_add = '''
#    source ~/.vim/rc/plugins/vimfiler.rc.vim
#'''
#
#[[plugins]]
#repo     = 'Shougo/unite.vim'
#hook_add = '''
#    source ~/.vim/rc/plugins/unite.rc.vim
#'''

[[plugins]]
repo     = 'itchyny/lightline.vim'
hook_add = '''
    source ~/.vim/rc/plugins/lightline.rc.vim
'''

[[plugins]]
repo     = 'nathanaelkane/vim-indent-guides'
hook_add = '''
    source ~/.vim/rc/plugins/indent_guides.rc.vim
'''

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'lilydjwg/colorizer'

[[plugins]]
repo = 'jpo/vim-railscasts-theme'

[[plugins]]
repo = 'tpope/vim-fugitive'

