[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
if   = '''! has('kaoriya')'''

    [plugins.build]
    windows = 'make -f make_mingw64.mak'
    cygwin  = 'make -f make_cygwin.mak'
    mac     = 'make -f make_mac.mak'
    linux   = 'make -f make_unix.mak'
    unix    = 'gmake -f make_unix.mak'

[[plugins]]
repo     = 'itchyny/lightline.vim'
hook_add = '''
    source ~/.vim/rc/plugins/lightline.rc.vim
'''

[[plugins]]
repo     = 'nathanaelkane/vim-indent-guides'
hook_add = '''
    source ~/.vim/rc/plugins/indent_guides.rc.vim
'''

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'lilydjwg/colorizer'

[[plugins]]
repo     = 'Shougo/vimfiler'
depends  = 'unite.vim'
hook_add = '''
    source ~/.vim/rc/plugins/vimfiler.rc.vim
'''

[[plugins]]
repo     = 'Shougo/unite.vim'
hook_add = '''
    source ~/.vim/rc/plugins/unite.rc.vim
'''

[[plugins]]
repo = 'jpo/vim-railscasts-theme'

[[plugins]]
repo = 'tpope/vim-fugitive'

