" Vim syntax file
" Language:		YamahaRT config
" Maintainer:	okkiroxx
" Last Change:	2016/7/9
" Credits:

setlocal iskeyword+=*,.,/,-

syn match	yamahaNumber	"\(\s\|,\|=\|-\|\[\)\@<=[0-9]\+\(\s\|,\|=\|\]\|/\|$\)\@="
syn match	yamahaString	\".*"\
syn match	yamahaTime		"[0-9]\{1,2}:[0-9]\{1,2}"
syn match	yamahaIPv4		"\d\{1,3}\.\d\{1,3}\.\d\{1,3}\.\d\{1,3}"
							\ nextgroup=yamahaSubnet
syn match	yamahaSubnet	"[0-9a-zA-Z]\@<=\/\d\{1,2}\(\s\|$\)\@="
syn match	yamahaEmail		"\S*@\S*"
syn match	yamahaURL		"\(\S\+\.\)\{1,}\S\+"
syn match	yamahaTunnel	"tunnel[0-9*]*"
syn match	yamahaVlan		"vlan[0-9*]*"
syn match	yamahaPP		"pp[0-9*]\+"
syn match	yamahaBRI		"bri[0-9*]\+\(\.[1-9]\)*"
syn match	yamahaPRI		"pri[0-9*]\+"
syn match	yamahaBridge	"bridge[0-9*]\+"
syn match	yamahaBind		"\(\s\|,\)\@<=[0-9]\+-[0-9]\+\(\s\|,\|$\)\@="
syn match	yamahaSplitinto	"split-into-[1-9:]\+"
syn match	yamahaPort		"\(tcp\|udp\)\/[0-9]\+"
syn match	yamahaBandwidth	"\(\s\|=\|,\)\@<=[0-9]\+m"

syn match	yamahaComment	"^#.*$"


syn keyword yamahaNumber	.
syn keyword yamahaNumber	*


syn keyword	yamahaBuiltin	3des-cbc
syn keyword	yamahaBuiltin	admin
syn keyword	yamahaBuiltin	aes-cbc
syn keyword	yamahaBuiltin	all
syn keyword	yamahaBuiltin	anonymous
syn keyword	yamahaBuiltin	anti-replay-check
syn keyword	yamahaBuiltin	any
syn keyword	yamahaBuiltin	auth-error
syn keyword	yamahaBuiltin	auto
syn keyword	yamahaBuiltin	bandwidth
syn keyword	yamahaBuiltin	call-waiting
syn keyword	yamahaBuiltin	chap
syn keyword	yamahaBuiltin	client
syn keyword	yamahaBuiltin	connection
syn keyword	yamahaBuiltin	control
syn keyword	yamahaBuiltin	count
syn keyword	yamahaBuiltin	default
syn match	yamahaBuiltin	"\(^\s*\)\@!\s\+dhcp"
syn match	yamahaBuiltin	"\(^\s*\)\@!\s\+dns"
syn keyword	yamahaBuiltin	divide-network
syn keyword	yamahaBuiltin	dhcpc
syn keyword	yamahaBuiltin	dhcps
syn keyword	yamahaBuiltin	domain
syn keyword	yamahaBuiltin	dynamic
syn keyword	yamahaBuiltin	economy
syn keyword	yamahaBuiltin	enable
syn keyword	yamahaBuiltin	esp
syn keyword	yamahaBuiltin	established
syn keyword	yamahaBuiltin	except
syn keyword	yamahaBuiltin	filter
syn keyword	yamahaBuiltin	fqdn
syn keyword	yamahaBuiltin	ftp
syn keyword	yamahaBuiltin	ftpdata
syn keyword	yamahaBuiltin	ftpdata-21
syn keyword	yamahaBuiltin	g711u
syn keyword	yamahaBuiltin	gateway
syn keyword	yamahaBuiltin	gre
syn keyword	yamahaBuiltin	group
syn keyword	yamahaBuiltin	heartbeat
syn keyword	yamahaBuiltin	high
syn keyword	yamahaBuiltin	host
syn keyword	yamahaBuiltin	http
syn keyword	yamahaBuiltin	https
syn keyword	yamahaBuiltin	hybrid
syn keyword	yamahaBuiltin	icmp
syn keyword	yamahaBuiltin	icmp6
syn keyword	yamahaBuiltin	icmp-echo
syn keyword	yamahaBuiltin	ident
syn keyword	yamahaBuiltin	ike
syn keyword	yamahaBuiltin	in
syn keyword	yamahaBuiltin	ir
syn keyword	yamahaBuiltin	include
syn keyword	yamahaBuiltin	ipudp
syn match	yamahaBuiltin	"\(^\s*\)\@!\s\+ip"
syn keyword	yamahaBuiltin	ipcp
syn keyword	yamahaBuiltin	isdn-ntt
syn keyword	yamahaBuiltin	isdn-terminal
syn keyword	yamahaBuiltin	join
syn keyword	yamahaBuiltin	keepalive
syn keyword	yamahaBuiltin	key
syn keyword	yamahaBuiltin	key-id
syn keyword	yamahaBuiltin	l128
syn match	yamahaBuiltin	"\(^\s*\)\@!\s\+l2tp"
syn match	yamahaBuiltin	"\(^\s*\)\@!\s\+l2tpv3"
syn match	yamahaBuiltin	"\(^\s*\)\@!\s\+l2tpv3-raw"
syn match	yamahaBuiltin	"\(^\s*\)\@!\s\+lan[1-9]*"
syn match	yamahaBuiltin	"\(^\s*\)\@!\s\+lan[1-9]\(\.\|:\)[1-9]"
syn match	yamahaBuiltin	"\(^\s*\)\@!\s\+line"
syn keyword	yamahaBuiltin	linkdown-recovery
syn keyword	yamahaBuiltin	local
syn keyword	yamahaBuiltin	low
syn keyword	yamahaBuiltin	masquerade
syn keyword	yamahaBuiltin	md5-hmac
syn keyword	yamahaBuiltin	mppe-any
syn keyword	yamahaBuiltin	mschap
syn keyword	yamahaBuiltin	mschap-v2
syn keyword	yamahaBuiltin	name
syn keyword	yamahaBuiltin	netbios_ns
syn keyword	yamahaBuiltin	netbios_ns-netbios_ssn
syn keyword	yamahaBuiltin	netbios_ssn
syn keyword	yamahaBuiltin	netbios_dgm
syn keyword	yamahaBuiltin	netmeeting
syn match	yamahaBuiltin	"\(^\s*\)\@!\s\+ngn"
syn keyword	yamahaBuiltin	nntp
syn keyword	yamahaBuiltin	none
syn keyword	yamahaBuiltin	normal
syn keyword	yamahaBuiltin	normal-number
syn keyword	yamahaBuiltin	ntp
syn keyword	yamahaBuiltin	ntpdate
syn keyword	yamahaBuiltin	ntt
syn keyword	yamahaBuiltin	off
syn keyword	yamahaBuiltin	o_flag
syn keyword	yamahaBuiltin	on
syn keyword	yamahaBuiltin	ospf
syn keyword	yamahaBuiltin	out
syn keyword	yamahaBuiltin	pap
syn keyword	yamahaBuiltin	pass
syn keyword	yamahaBuiltin	pass-log
syn keyword	yamahaBuiltin	pass-nolog
syn keyword	yamahaBuiltin	plain
syn keyword	yamahaBuiltin	pop3
syn keyword	yamahaBuiltin	pool
syn keyword	yamahaBuiltin	port
syn match	yamahaBuiltin	"\(^\s*\)\@!\s\+pp\(\s\|$\)\@="
syn match	yamahaBuiltin	"\(^\s*\)\@!\s\+pptp"
syn keyword	yamahaBuiltin	precedence
syn keyword	yamahaBuiltin	prefix
syn keyword	yamahaBuiltin	priority
syn keyword	yamahaBuiltin	primary
syn match	yamahaBuiltin	"\(^\s*\)\@!\s\+provider"
syn keyword	yamahaBuiltin	public
syn keyword	yamahaBuiltin	recieve
syn keyword	yamahaBuiltin	recursive
syn keyword	yamahaBuiltin	reject
syn keyword	yamahaBuiltin	reject-nolog
syn keyword	yamahaBuiltin	remain-silent
syn keyword	yamahaBuiltin	retry-interval
syn keyword	yamahaBuiltin	restrict
syn keyword	yamahaBuiltin	route
syn keyword	yamahaBuiltin	route-table
syn keyword	yamahaBuiltin	router
syn keyword	yamahaBuiltin	routing
syn keyword	yamahaBuiltin	server
syn keyword	yamahaBuiltin	sha
syn keyword	yamahaBuiltin	sha-hmac
syn keyword	yamahaBuiltin	shaping
syn match	yamahaBuiltin	"\(^\s*\)\@!\s\+sip"
syn keyword	yamahaBuiltin	smtp
syn keyword	yamahaBuiltin	smtp-auth
syn keyword	yamahaBuiltin	static
syn keyword	yamahaBuiltin	static-pass
syn keyword	yamahaBuiltin	static-pass-log
syn keyword	yamahaBuiltin	static-pass-nolog
syn keyword	yamahaBuiltin	submission
syn keyword	yamahaBuiltin	switch-interface
syn keyword	yamahaBuiltin	switch-router
syn match	yamahaBuiltin	"\(^\s*\)\@!\s\+syslog"
syn keyword	yamahaBuiltin	tel
syn keyword	yamahaBuiltin	tel-key
syn keyword	yamahaBuiltin	telnet
syn keyword	yamahaBuiltin	tcp
syn keyword	yamahaBuiltin	tcpfin
syn keyword	yamahaBuiltin	tcpflag
syn keyword	yamahaBuiltin	tcprst
syn keyword	yamahaBuiltin	text
syn keyword	yamahaBuiltin	trigger
syn keyword	yamahaBuiltin	udp
syn keyword	yamahaBuiltin	vid
syn keyword	yamahaBuiltin	version
syn keyword	yamahaBuiltin	weight
syn keyword	yamahaBuiltin	www


syn match	yamahaStatement		"^\s*administrator"
syn match	yamahaStatement		"^\s*administrator password"
syn match	yamahaStatement		"^\s*administrator password encrypted"
syn match	yamahaStatement		"^\s*administrator radius auth"
syn match	yamahaStatement		"^\s*alarm batch"
syn match	yamahaStatement		"^\s*alarm connection data"
syn match	yamahaStatement		"^\s*alarm entire"
syn match	yamahaStatement		"^\s*alarm http revision-up"
syn match	yamahaStatement		"^\s*alarm lua"
syn match	yamahaStatement		"^\s*alarm mobile"
syn match	yamahaStatement		"^\s*alarm sd"
syn match	yamahaStatement		"^\s*alarm startup"
syn match	yamahaStatement		"^\s*alarm usbhost"
syn match	yamahaStatement		"^\s*alarm usbhost"
syn match	yamahaStatement		"^\s*analog call"
syn match	yamahaStatement		"^\s*analog supplementary-service pseudo"
syn match	yamahaStatement		"^\s*analog extension dial prefix"
syn match	yamahaStatement		"^\s*analog extension emergency-call-dial type"
syn match	yamahaStatement		"^\s*ap config directory"
syn match	yamahaStatement		"^\s*ap config filename"
syn match	yamahaStatement		"^\s*ap control config delete"
syn match	yamahaStatement		"^\s*ap control config get"
syn match	yamahaStatement		"^\s*ap control config set"
syn match	yamahaStatement		"^\s*ap control config-auto-set use"
syn match	yamahaStatement		"^\s*ap control firmware update go"
syn match	yamahaStatement		"^\s*ap control http proxy timeout"
syn match	yamahaStatement		"^\s*ap control http proxy use"
syn match	yamahaStatement		"^\s*ap select"
syn match	yamahaStatement		"^\s*auth user"
syn match	yamahaStatement		"^\s*auth user attribute"
syn match	yamahaStatement		"^\s*auth user group"
syn match	yamahaStatement		"^\s*auth user group attribute"
syn match	yamahaStatement		"^\s*bgp aggregate"
syn match	yamahaStatement		"^\s*bgp aggregate filter"
syn match	yamahaStatement		"^\s*bgp autonomous-system"
syn match	yamahaStatement		"^\s*bgp configure refresh"
syn match	yamahaStatement		"^\s*bgp export"
syn match	yamahaStatement		"^\s*bgp export aspath"
syn match	yamahaStatement		"^\s*bgp export filter"
syn match	yamahaStatement		"^\s*bgp import"
syn match	yamahaStatement		"^\s*bgp import filter"
syn match	yamahaStatement		"^\s*bgp log"
syn match	yamahaStatement		"^\s*bgp neighbor"
syn match	yamahaStatement		"^\s*bgp preference"
syn match	yamahaStatement		"^\s*bgp router id"
syn match	yamahaStatement		"^\s*bgp use"
syn match	yamahaStatement		"^\s*bridge learning"
syn match	yamahaStatement		"^\s*bridge learning .* static"
syn match	yamahaStatement		"^\s*bridge learning .* timer"
syn match	yamahaStatement		"^\s*bridge member"
syn match	yamahaStatement		"^\s*clear account"
syn match	yamahaStatement		"^\s*clear account mobile"
syn match	yamahaStatement		"^\s*clear account ngn data"
syn match	yamahaStatement		"^\s*clear account pp"
syn match	yamahaStatement		"^\s*clear arp"
syn match	yamahaStatement		"^\s*clear boot list"
syn match	yamahaStatement		"^\s*clear bridge learning"
syn match	yamahaStatement		"^\s*clear dns cache"
syn match	yamahaStatement		"^\s*clear external-memory syslog"
syn match	yamahaStatement		"^\s*clear heartbeat2"
syn match	yamahaStatement		"^\s*clear ip dynamic routing"
syn match	yamahaStatement		"^\s*clear ipv6 dynamic routing"
syn match	yamahaStatement		"^\s*clear ipv6 neighbor cache"
syn match	yamahaStatement		"^\s*clear log"
syn match	yamahaStatement		"^\s*clear mobile access limitation"
syn match	yamahaStatement		"^\s*clear mobile access limitation pp"
syn match	yamahaStatement		"^\s*clear nat descriptor dynamic"
syn match	yamahaStatement		"^\s*clear nat descriptor interface dynamic pp"
syn match	yamahaStatement		"^\s*clear nat descriptor interface dynamic tunnel"
syn match	yamahaStatement		"^\s*clear nat descriptor interface dynamic wan1"
syn match	yamahaStatement		"^\s*clear nat descriptor interface dynamic"
syn match	yamahaStatement		"^\s*clear status pp"
syn match	yamahaStatement		"^\s*clear status tunnel"
syn match	yamahaStatement		"^\s*clear status wan1"
syn match	yamahaStatement		"^\s*clear status"
syn match	yamahaStatement		"^\s*clear switching-hub macaddress"
syn match	yamahaStatement		"^\s*clear url filter"
syn match	yamahaStatement		"^\s*cold start"
syn match	yamahaStatement		"^\s*connect"
syn match	yamahaStatement		"^\s*console character"
syn match	yamahaStatement		"^\s*console columns"
syn match	yamahaStatement		"^\s*console info"
syn match	yamahaStatement		"^\s*console lines"
syn match	yamahaStatement		"^\s*console prompt"
syn match	yamahaStatement		"^\s*cooperation bandwidth-measuring"
syn match	yamahaStatement		"^\s*cooperation bandwidth-measuring go"
syn match	yamahaStatement		"^\s*cooperation bandwidth-measuring remote"
syn match	yamahaStatement		"^\s*cooperation load-watch"
syn match	yamahaStatement		"^\s*cooperation load-watch control"
syn match	yamahaStatement		"^\s*cooperation load-watch go"
syn match	yamahaStatement		"^\s*cooperation load-watch remote"
syn match	yamahaStatement		"^\s*cooperation load-watch trigger"
syn match	yamahaStatement		"^\s*cooperation port"
syn match	yamahaStatement		"^\s*copy"
syn match	yamahaStatement		"^\s*copy config"
syn match	yamahaStatement		"^\s*copy exec"
syn match	yamahaStatement		"^\s*date"
syn match	yamahaStatement		"^\s*delete"
syn match	yamahaStatement		"^\s*delete config"
syn match	yamahaStatement		"^\s*description"
syn match	yamahaStatement		"^\s*description pp"
syn match	yamahaStatement		"^\s*description tunnel"
syn match	yamahaStatement		"^\s*description wan1"
syn match	yamahaStatement		"^\s*description"
syn match	yamahaStatement		"^\s*dhcp client client-identifier"
syn match	yamahaStatement		"^\s*dhcp client hostname"
syn match	yamahaStatement		"^\s*dhcp client option"
syn match	yamahaStatement		"^\s*dhcp client release linkdown"
syn match	yamahaStatement		"^\s*dhcp convert"
syn match	yamahaStatement		"^\s*dhcp duplicate check"
syn match	yamahaStatement		"^\s*dhcp manual lease"
syn match	yamahaStatement		"^\s*dhcp manual release"
syn match	yamahaStatement		"^\s*dhcp relay select"
syn match	yamahaStatement		"^\s*dhcp relay server"
syn match	yamahaStatement		"^\s*dhcp relay threshold"
syn match	yamahaStatement		"^\s*dhcp scope"
syn match	yamahaStatement		"^\s*dhcp scope bind"
syn match	yamahaStatement		"^\s*dhcp scope lease type"
syn match	yamahaStatement		"^\s*dhcp scope option"
syn match	yamahaStatement		"^\s*dhcp server"
syn match	yamahaStatement		"^\s*dhcp server rfc2131 compliant"
syn match	yamahaStatement		"^\s*dhcp service"
syn match	yamahaStatement		"^\s*disconnect"
syn match	yamahaStatement		"^\s*disconnect ip connection"
syn match	yamahaStatement		"^\s*disconnect ipv6 connection"
syn match	yamahaStatement		"^\s*disconnect user"
syn match	yamahaStatement		"^\s*dns cache max entry"
syn match	yamahaStatement		"^\s*dns cache use"
syn match	yamahaStatement		"^\s*dns domain"
syn match	yamahaStatement		"^\s*dns host"
syn match	yamahaStatement		"^\s*dns notice order"
syn match	yamahaStatement		"^\s*dns private address spoof"
syn match	yamahaStatement		"^\s*dns private name"
syn match	yamahaStatement		"^\s*dns server"
syn match	yamahaStatement		"^\s*dns server dhcp"
syn match	yamahaStatement		"^\s*dns server pp"
syn match	yamahaStatement		"^\s*dns server select"
syn match	yamahaStatement		"^\s*dns service"
syn match	yamahaStatement		"^\s*dns service fallback"
syn match	yamahaStatement		"^\s*dns srcport"
syn match	yamahaStatement		"^\s*dns static"
syn match	yamahaStatement		"^\s*dns syslog resolv"
syn match	yamahaStatement		"^\s*ethernet filter"
syn match	yamahaStatement		"^\s*ethernet .* filter"
syn match	yamahaStatement		"^\s*execute at-command"
syn match	yamahaStatement		"^\s*execute batch"
syn match	yamahaStatement		"^\s*exit"
syn match	yamahaStatement		"^\s*external-memory accelerator cache size"
syn match	yamahaStatement		"^\s*external-memory auto-search time"
syn match	yamahaStatement		"^\s*external-memory batch filename"
syn match	yamahaStatement		"^\s*external-memory boot permit"
syn match	yamahaStatement		"^\s*external-memory boot timeout"
syn match	yamahaStatement		"^\s*external-memory cache mode"
syn match	yamahaStatement		"^\s*external-memory config filename"
syn match	yamahaStatement		"^\s*external-memory exec filename"
syn match	yamahaStatement		"^\s*external-memory performance-test go"
syn match	yamahaStatement		"^\s*external-memory syslog filename"
syn match	yamahaStatement		"^\s*grep"
syn match	yamahaStatement		"^\s*heartbeat pre-shared-key"
syn match	yamahaStatement		"^\s*heartbeat receive"
syn match	yamahaStatement		"^\s*heartbeat send"
syn match	yamahaStatement		"^\s*heartbeat2 myname"
syn match	yamahaStatement		"^\s*heartbeat2 receive"
syn match	yamahaStatement		"^\s*heartbeat2 receive enable"
syn match	yamahaStatement		"^\s*heartbeat2 receive log"
syn match	yamahaStatement		"^\s*heartbeat2 receive monitor"
syn match	yamahaStatement		"^\s*heartbeat2 receive record limit"
syn match	yamahaStatement		"^\s*heartbeat2 transmit"
syn match	yamahaStatement		"^\s*heartbeat2 transmit enable"
syn match	yamahaStatement		"^\s*heartbeat2 transmit interval"
syn match	yamahaStatement		"^\s*heartbeat2 transmit log"
syn match	yamahaStatement		"^\s*help"
syn match	yamahaStatement		"^\s*http revision-down permit"
syn match	yamahaStatement		"^\s*http revision-up go"
syn match	yamahaStatement		"^\s*http revision-up permit"
syn match	yamahaStatement		"^\s*http revision-up proxy"
syn match	yamahaStatement		"^\s*http revision-up schedule"
syn match	yamahaStatement		"^\s*http revision-up timeout"
syn match	yamahaStatement		"^\s*http revision-up url"
syn match	yamahaStatement		"^\s*httpd custom-gui api password"
syn match	yamahaStatement		"^\s*httpd custom-gui api use"
syn match	yamahaStatement		"^\s*httpd custom-gui use"
syn match	yamahaStatement		"^\s*httpd custom-gui user"
syn match	yamahaStatement		"^\s*httpd host"
syn match	yamahaStatement		"^\s*httpd listen"
syn match	yamahaStatement		"^\s*httpd service"
syn match	yamahaStatement		"^\s*httpd timeout"
syn match	yamahaStatement		"^\s*interface reset"
syn match	yamahaStatement		"^\s*ip arp timer"
syn match	yamahaStatement		"^\s*ip filter"
syn match	yamahaStatement		"^\s*ip filter directed-broadcast"
syn match	yamahaStatement		"^\s*ip filter dynamic"
syn match	yamahaStatement		"^\s*ip filter dynamic timer"
syn match	yamahaStatement		"^\s*ip filter set"
syn match	yamahaStatement		"^\s*ip filter source-route"
syn match	yamahaStatement		"^\s*ip flow timer"
syn match	yamahaStatement		"^\s*ip forward filter"
syn match	yamahaStatement		"^\s*ip fragment remove df-bit"
syn match	yamahaStatement		"^\s*ip host"
syn match	yamahaStatement		"^\s*ip icmp echo-reply send"
syn match	yamahaStatement		"^\s*ip icmp echo-reply send-only-linkup"
syn match	yamahaStatement		"^\s*ip icmp error-decrypted-ipsec send"
syn match	yamahaStatement		"^\s*ip icmp log"
syn match	yamahaStatement		"^\s*ip icmp mask-reply send"
syn match	yamahaStatement		"^\s*ip icmp parameter-problem send"
syn match	yamahaStatement		"^\s*ip icmp redirect receive"
syn match	yamahaStatement		"^\s*ip icmp redirect send"
syn match	yamahaStatement		"^\s*ip icmp time-exceeded send"
syn match	yamahaStatement		"^\s*ip icmp timestamp-reply send"
syn match	yamahaStatement		"^\s*ip icmp unreachable send"
syn match	yamahaStatement		"^\s*ip implicit-route preference"
syn match	yamahaStatement		"^\s*ip inbound filter"
syn match	yamahaStatement		"^\s*ip keepalive"
syn match	yamahaStatement		"^\s*ip v*lan[1-9]\(/[1-9]\)* address"
syn match	yamahaStatement		"^\s*ip v*lan[1-9]\(/[1-9]\)* proxyarp"
syn match	yamahaStatement		"^\s*ip v*lan[1-9]\(/[1-9]\)* secure filter"
syn match	yamahaStatement		"^\s*ip local forward filter"
syn match	yamahaStatement		"^\s*ip loopback1 address"
syn match	yamahaStatement		"^\s*ip loopback1 ospf area"
syn match	yamahaStatement		"^\s*ip loopback1 secure filter"
syn match	yamahaStatement		"^\s*ip loopback2 address"
syn match	yamahaStatement		"^\s*ip loopback2 ospf area"
syn match	yamahaStatement		"^\s*ip loopback2 secure filter"
syn match	yamahaStatement		"^\s*ip loopback3 address"
syn match	yamahaStatement		"^\s*ip loopback3 ospf area"
syn match	yamahaStatement		"^\s*ip loopback3 secure filter"
syn match	yamahaStatement		"^\s*ip loopback4 address"
syn match	yamahaStatement		"^\s*ip loopback4 ospf area"
syn match	yamahaStatement		"^\s*ip loopback4 secure filter"
syn match	yamahaStatement		"^\s*ip loopback5 address"
syn match	yamahaStatement		"^\s*ip loopback5 ospf area"
syn match	yamahaStatement		"^\s*ip loopback5 secure filter"
syn match	yamahaStatement		"^\s*ip loopback6 address"
syn match	yamahaStatement		"^\s*ip loopback6 ospf area"
syn match	yamahaStatement		"^\s*ip loopback6 secure filter"
syn match	yamahaStatement		"^\s*ip loopback7 address"
syn match	yamahaStatement		"^\s*ip loopback7 ospf area"
syn match	yamahaStatement		"^\s*ip loopback7 secure filter"
syn match	yamahaStatement		"^\s*ip loopback8 address"
syn match	yamahaStatement		"^\s*ip loopback8 ospf area"
syn match	yamahaStatement		"^\s*ip loopback8 secure filter"
syn match	yamahaStatement		"^\s*ip loopback9 address"
syn match	yamahaStatement		"^\s*ip loopback9 ospf area"
syn match	yamahaStatement		"^\s*ip loopback9 secure filter"
syn match	yamahaStatement		"^\s*ip null secure filter"
syn match	yamahaStatement		"^\s*ip policy address group"
syn match	yamahaStatement		"^\s*ip policy filter"
syn match	yamahaStatement		"^\s*ip policy filter set"
syn match	yamahaStatement		"^\s*ip policy interface group"
syn match	yamahaStatement		"^\s*ip policy service group"
syn match	yamahaStatement		"^\s*ip pp address"
syn match	yamahaStatement		"^\s*ip pp forward filter"
syn match	yamahaStatement		"^\s*ip pp inbound filter list"
syn match	yamahaStatement		"^\s*ip pp intrusion detection"
syn match	yamahaStatement		"^\s*ip pp intrusion detection notice-interval"
syn match	yamahaStatement		"^\s*ip pp intrusion detection repeat-control"
syn match	yamahaStatement		"^\s*ip pp intrusion detection report"
syn match	yamahaStatement		"^\s*ip pp intrusion detection threshold"
syn match	yamahaStatement		"^\s*ip pp mtu"
syn match	yamahaStatement		"^\s*ip pp nat descriptor"
syn match	yamahaStatement		"^\s*ip pp ospf area"
syn match	yamahaStatement		"^\s*ip pp ospf neighbor"
syn match	yamahaStatement		"^\s*ip pp rebound"
syn match	yamahaStatement		"^\s*ip pp remote address"
syn match	yamahaStatement		"^\s*ip pp remote address pool"
syn match	yamahaStatement		"^\s*ip pp rip auth key"
syn match	yamahaStatement		"^\s*ip pp rip auth type"
syn match	yamahaStatement		"^\s*ip pp rip backup interface"
syn match	yamahaStatement		"^\s*ip pp rip connect interval"
syn match	yamahaStatement		"^\s*ip pp rip connect send"
syn match	yamahaStatement		"^\s*ip pp rip disconnect interval"
syn match	yamahaStatement		"^\s*ip pp rip disconnect send"
syn match	yamahaStatement		"^\s*ip pp rip filter"
syn match	yamahaStatement		"^\s*ip pp rip force-to-advertise"
syn match	yamahaStatement		"^\s*ip pp rip hold routing"
syn match	yamahaStatement		"^\s*ip pp rip hop"
syn match	yamahaStatement		"^\s*ip pp rip receive"
syn match	yamahaStatement		"^\s*ip pp rip send"
syn match	yamahaStatement		"^\s*ip pp rip trust gateway"
syn match	yamahaStatement		"^\s*ip pp secure filter"
syn match	yamahaStatement		"^\s*ip pp tcp mss limit"
syn match	yamahaStatement		"^\s*ip route"
syn match	yamahaStatement		"^\s*ip route change log"
syn match	yamahaStatement		"^\s*ip routing"
syn match	yamahaStatement		"^\s*ip routing process"
syn match	yamahaStatement		"^\s*ip simple-service"
syn match	yamahaStatement		"^\s*ip stealth"
syn match	yamahaStatement		"^\s*ip tos supersede"
syn match	yamahaStatement		"^\s*ip tunnel address"
syn match	yamahaStatement		"^\s*ip tunnel forward filter"
syn match	yamahaStatement		"^\s*ip tunnel intrusion detection"
syn match	yamahaStatement		"^\s*ip tunnel intrusion detection notice-interval"
syn match	yamahaStatement		"^\s*ip tunnel intrusion detection repeat-control"
syn match	yamahaStatement		"^\s*ip tunnel intrusion detection report"
syn match	yamahaStatement		"^\s*ip tunnel intrusion detection threshold"
syn match	yamahaStatement		"^\s*ip tunnel mtu"
syn match	yamahaStatement		"^\s*ip tunnel nat descriptor"
syn match	yamahaStatement		"^\s*ip tunnel ospf area"
syn match	yamahaStatement		"^\s*ip tunnel ospf neighbor"
syn match	yamahaStatement		"^\s*ip tunnel rebound"
syn match	yamahaStatement		"^\s*ip tunnel remote address"
syn match	yamahaStatement		"^\s*ip tunnel rip auth key"
syn match	yamahaStatement		"^\s*ip tunnel rip auth type"
syn match	yamahaStatement		"^\s*ip tunnel rip filter"
syn match	yamahaStatement		"^\s*ip tunnel rip force-to-advertise"
syn match	yamahaStatement		"^\s*ip tunnel rip hop"
syn match	yamahaStatement		"^\s*ip tunnel rip receive"
syn match	yamahaStatement		"^\s*ip tunnel rip send"
syn match	yamahaStatement		"^\s*ip tunnel rip trust gateway"
syn match	yamahaStatement		"^\s*ip tunnel secure filter"
syn match	yamahaStatement		"^\s*ip tunnel tcp mss limit"
syn match	yamahaStatement		"^\s*ip wan1 address"
syn match	yamahaStatement		"^\s*ip wan1 dhcp lease time"
syn match	yamahaStatement		"^\s*ip wan1 dhcp retry"
syn match	yamahaStatement		"^\s*ip wan1 forward filter"
syn match	yamahaStatement		"^\s*ip wan1 intrusion detection"
syn match	yamahaStatement		"^\s*ip wan1 intrusion detection notice-interval"
syn match	yamahaStatement		"^\s*ip wan1 intrusion detection repeat-control"
syn match	yamahaStatement		"^\s*ip wan1 intrusion detection report"
syn match	yamahaStatement		"^\s*ip wan1 intrusion detection threshold"
syn match	yamahaStatement		"^\s*ip wan1 mtu"
syn match	yamahaStatement		"^\s*ip wan1 nat descriptor"
syn match	yamahaStatement		"^\s*ip wan1 secure filter"
syn match	yamahaStatement		"^\s*ip wan1 tcp mss limit"
syn match	yamahaStatement		"^\s*ip bridge[1-9] address"
syn match	yamahaStatement		"^\s*ip .* arp log"
syn match	yamahaStatement		"^\s*ip .* arp queue length"
syn match	yamahaStatement		"^\s*ip .* arp static"
syn match	yamahaStatement		"^\s*ip .* forward filter"
syn match	yamahaStatement		"^\s*ip .* intrusion detection"
syn match	yamahaStatement		"^\s*ip .* intrusion detection notice-interval"
syn match	yamahaStatement		"^\s*ip .* intrusion detection repeat-control"
syn match	yamahaStatement		"^\s*ip .* intrusion detection report"
syn match	yamahaStatement		"^\s*ip .* intrusion detection threshold"
syn match	yamahaStatement		"^\s*ip .* mtu"
syn match	yamahaStatement		"^\s*ip .* nat descriptor"
syn match	yamahaStatement		"^\s*ip .* ospf area"
syn match	yamahaStatement		"^\s*ip .* ospf neighbor"
syn match	yamahaStatement		"^\s*ip .* rebound"
syn match	yamahaStatement		"^\s*ip .* rip auth key"
syn match	yamahaStatement		"^\s*ip .* rip auth type"
syn match	yamahaStatement		"^\s*ip .* rip filter"
syn match	yamahaStatement		"^\s*ip .* rip force-to-advertise"
syn match	yamahaStatement		"^\s*ip .* rip hop"
syn match	yamahaStatement		"^\s*ip .* rip receive"
syn match	yamahaStatement		"^\s*ip .* rip send"
syn match	yamahaStatement		"^\s*ip .* rip trust gateway"
syn match	yamahaStatement		"^\s*ip .* secondary address"
syn match	yamahaStatement		"^\s*ip .* tcp mss limit"
syn match	yamahaStatement		"^\s*ip .* vrrp"
syn match	yamahaStatement		"^\s*ip .* vrrp shutdown trigger"
syn match	yamahaStatement		"^\s*ip .* wol relay"
syn match	yamahaStatement		"^\s*ip .* dhcp lease time"
syn match	yamahaStatement		"^\s*ip .* dhcp retry"
syn match	yamahaStatement		"^\s*ip .* proxyarp"
syn match	yamahaStatement		"^\s*ip .* secure filter"
syn match	yamahaStatement		"^\s*ipsec auto refresh"
syn match	yamahaStatement		"^\s*ipsec ike always-on"
syn match	yamahaStatement		"^\s*ipsec ike auth method"
syn match	yamahaStatement		"^\s*ipsec ike backward-compatibility"
syn match	yamahaStatement		"^\s*ipsec ike duration"
syn match	yamahaStatement		"^\s*ipsec ike eap myname"
syn match	yamahaStatement		"^\s*ipsec ike eap request"
syn match	yamahaStatement		"^\s*ipsec ike eap send certreq"
syn match	yamahaStatement		"^\s*ipsec ike encryption"
syn match	yamahaStatement		"^\s*ipsec ike esp-encapsulation"
syn match	yamahaStatement		"^\s*ipsec ike group"
syn match	yamahaStatement		"^\s*ipsec ike hash"
syn match	yamahaStatement		"^\s*ipsec ike keepalive log"
syn match	yamahaStatement		"^\s*ipsec ike keepalive use"
syn match	yamahaStatement		"^\s*ipsec ike local address"
syn match	yamahaStatement		"^\s*ipsec ike local id"
syn match	yamahaStatement		"^\s*ipsec ike local name"
syn match	yamahaStatement		"^\s*ipsec ike log"
syn match	yamahaStatement		"^\s*ipsec ike message-id-control"
syn match	yamahaStatement		"^\s*ipsec ike mode-cfg address"
syn match	yamahaStatement		"^\s*ipsec ike mode-cfg address pool"
syn match	yamahaStatement		"^\s*ipsec ike mode-cfg method"
syn match	yamahaStatement		"^\s*ipsec ike nat-traversal"
syn match	yamahaStatement		"^\s*ipsec ike negotiate-strictly"
syn match	yamahaStatement		"^\s*ipsec ike payload type"
syn match	yamahaStatement		"^\s*ipsec ike pfs"
syn match	yamahaStatement		"^\s*ipsec ike pki file"
syn match	yamahaStatement		"^\s*ipsec ike pre-shared-key"
syn match	yamahaStatement		"^\s*ipsec ike proposal-limitation"
syn match	yamahaStatement		"^\s*ipsec ike queue length"
syn match	yamahaStatement		"^\s*ipsec ike remote address"
syn match	yamahaStatement		"^\s*ipsec ike remote id"
syn match	yamahaStatement		"^\s*ipsec ike remote name"
syn match	yamahaStatement		"^\s*ipsec ike restrict-dangling-sa"
syn match	yamahaStatement		"^\s*ipsec ike retry"
syn match	yamahaStatement		"^\s*ipsec ike send info"
syn match	yamahaStatement		"^\s*ipsec ike version"
syn match	yamahaStatement		"^\s*ipsec ike xauth myname"
syn match	yamahaStatement		"^\s*ipsec ike xauth request"
syn match	yamahaStatement		"^\s*ipsec ipcomp type"
syn match	yamahaStatement		"^\s*ipsec log illegal-spi"
syn match	yamahaStatement		"^\s*ipsec refresh sa"
syn match	yamahaStatement		"^\s*ipsec sa delete"
syn match	yamahaStatement		"^\s*ipsec sa policy"
syn match	yamahaStatement		"^\s*ipsec transport"
syn match	yamahaStatement		"^\s*ipsec transport template"
syn match	yamahaStatement		"^\s*ipsec tunnel"
syn match	yamahaStatement		"^\s*ipsec tunnel fastpath-fragment-function follow df-bit"
syn match	yamahaStatement		"^\s*ipsec tunnel outer df-bit"
syn match	yamahaStatement		"^\s*ipsec use"
syn match	yamahaStatement		"^\s*ipv6 filter"
syn match	yamahaStatement		"^\s*ipv6 filter dynamic"
syn match	yamahaStatement		"^\s*ipv6 icmp echo-reply send"
syn match	yamahaStatement		"^\s*ipv6 icmp echo-reply send-only-linkup"
syn match	yamahaStatement		"^\s*ipv6 icmp error-decrypted-ipsec send"
syn match	yamahaStatement		"^\s*ipv6 icmp log"
syn match	yamahaStatement		"^\s*ipv6 icmp packet-too-big send"
syn match	yamahaStatement		"^\s*ipv6 icmp parameter-problem send"
syn match	yamahaStatement		"^\s*ipv6 icmp redirect receive"
syn match	yamahaStatement		"^\s*ipv6 icmp redirect send"
syn match	yamahaStatement		"^\s*ipv6 icmp time-exceeded send"
syn match	yamahaStatement		"^\s*ipv6 icmp unreachable send"
syn match	yamahaStatement		"^\s*ipv6 lan[1-9] address"
syn match	yamahaStatement		"^\s*ipv6 lan[1-9] mld router version"
syn match	yamahaStatement		"^\s*ipv6 lan[1-9] mld host version"
syn match	yamahaStatement		"^\s*ipv6 lan[1-9] rtadv send"
syn match	yamahaStatement		"^\s*ipv6 loopback1 address"
syn match	yamahaStatement		"^\s*ipv6 loopback1 secure filter"
syn match	yamahaStatement		"^\s*ipv6 loopback2 address"
syn match	yamahaStatement		"^\s*ipv6 loopback2 secure filter"
syn match	yamahaStatement		"^\s*ipv6 loopback3 address"
syn match	yamahaStatement		"^\s*ipv6 loopback3 secure filter"
syn match	yamahaStatement		"^\s*ipv6 loopback4 address"
syn match	yamahaStatement		"^\s*ipv6 loopback4 secure filter"
syn match	yamahaStatement		"^\s*ipv6 loopback5 address"
syn match	yamahaStatement		"^\s*ipv6 loopback5 secure filter"
syn match	yamahaStatement		"^\s*ipv6 loopback6 address"
syn match	yamahaStatement		"^\s*ipv6 loopback6 secure filter"
syn match	yamahaStatement		"^\s*ipv6 loopback7 address"
syn match	yamahaStatement		"^\s*ipv6 loopback7 secure filter"
syn match	yamahaStatement		"^\s*ipv6 loopback8 address"
syn match	yamahaStatement		"^\s*ipv6 loopback8 secure filter"
syn match	yamahaStatement		"^\s*ipv6 loopback9 address"
syn match	yamahaStatement		"^\s*ipv6 loopback9 secure filter"
syn match	yamahaStatement		"^\s*ipv6 max auto address"
syn match	yamahaStatement		"^\s*ipv6 nd ns-trigger-dad"
syn match	yamahaStatement		"^\s*ipv6 null secure filter"
syn match	yamahaStatement		"^\s*ipv6 ospf area"
syn match	yamahaStatement		"^\s*ipv6 ospf area network"
syn match	yamahaStatement		"^\s*ipv6 ospf configure refresh"
syn match	yamahaStatement		"^\s*ipv6 ospf export filter"
syn match	yamahaStatement		"^\s*ipv6 ospf export from"
syn match	yamahaStatement		"^\s*ipv6 ospf import filter"
syn match	yamahaStatement		"^\s*ipv6 ospf import from"
syn match	yamahaStatement		"^\s*ipv6 ospf log"
syn match	yamahaStatement		"^\s*ipv6 ospf preference"
syn match	yamahaStatement		"^\s*ipv6 ospf router id"
syn match	yamahaStatement		"^\s*ipv6 ospf use"
syn match	yamahaStatement		"^\s*ipv6 ospf virtual-link"
syn match	yamahaStatement		"^\s*ipv6 pp address"
syn match	yamahaStatement		"^\s*ipv6 pp dad retry count"
syn match	yamahaStatement		"^\s*ipv6 pp dhcp service"
syn match	yamahaStatement		"^\s*ipv6 pp mld"
syn match	yamahaStatement		"^\s*ipv6 pp mld static"
syn match	yamahaStatement		"^\s*ipv6 pp mtu"
syn match	yamahaStatement		"^\s*ipv6 pp ospf area"
syn match	yamahaStatement		"^\s*ipv6 pp prefix"
syn match	yamahaStatement		"^\s*ipv6 pp prefix change log"
syn match	yamahaStatement		"^\s*ipv6 pp rip connect interval"
syn match	yamahaStatement		"^\s*ipv6 pp rip connect send"
syn match	yamahaStatement		"^\s*ipv6 pp rip disconnect interval"
syn match	yamahaStatement		"^\s*ipv6 pp rip disconnect send"
syn match	yamahaStatement		"^\s*ipv6 pp rip filter"
syn match	yamahaStatement		"^\s*ipv6 pp rip hold routing"
syn match	yamahaStatement		"^\s*ipv6 pp rip hop"
syn match	yamahaStatement		"^\s*ipv6 pp rip receive"
syn match	yamahaStatement		"^\s*ipv6 pp rip send"
syn match	yamahaStatement		"^\s*ipv6 pp rip trust gateway"
syn match	yamahaStatement		"^\s*ipv6 pp rtadv send"
syn match	yamahaStatement		"^\s*ipv6 pp secure filter"
syn match	yamahaStatement		"^\s*ipv6 pp tcp mss limit"
syn match	yamahaStatement		"^\s*ipv6 prefix"
syn match	yamahaStatement		"^\s*ipv6 rh0 discard"
syn match	yamahaStatement		"^\s*ipv6 rip preference"
syn match	yamahaStatement		"^\s*ipv6 rip use"
syn match	yamahaStatement		"^\s*ipv6 route"
syn match	yamahaStatement		"^\s*ipv6 routing"
syn match	yamahaStatement		"^\s*ipv6 routing process"
syn match	yamahaStatement		"^\s*ipv6 source address selection rule"
syn match	yamahaStatement		"^\s*ipv6 stealth"
syn match	yamahaStatement		"^\s*ipv6 tunnel address"
syn match	yamahaStatement		"^\s*ipv6 tunnel dhcp service"
syn match	yamahaStatement		"^\s*ipv6 tunnel mld"
syn match	yamahaStatement		"^\s*ipv6 tunnel mld static"
syn match	yamahaStatement		"^\s*ipv6 tunnel ospf area"
syn match	yamahaStatement		"^\s*ipv6 tunnel prefix"
syn match	yamahaStatement		"^\s*ipv6 tunnel prefix change log"
syn match	yamahaStatement		"^\s*ipv6 tunnel rip filter"
syn match	yamahaStatement		"^\s*ipv6 tunnel rip receive"
syn match	yamahaStatement		"^\s*ipv6 tunnel rip send"
syn match	yamahaStatement		"^\s*ipv6 tunnel secure filter"
syn match	yamahaStatement		"^\s*ipv6 tunnel tcp mss limit"
syn match	yamahaStatement		"^\s*ipv6 .* dhcp service"
syn match	yamahaStatement		"^\s*ipv6 .* mld"
syn match	yamahaStatement		"^\s*ipv6 .* mld static"
syn match	yamahaStatement		"^\s*ipv6 .* mtu"
syn match	yamahaStatement		"^\s*ipv6 .* ospf area"
syn match	yamahaStatement		"^\s*ipv6 .* rip filter"
syn match	yamahaStatement		"^\s*ipv6 .* rip hop"
syn match	yamahaStatement		"^\s*ipv6 .* rip receive"
syn match	yamahaStatement		"^\s*ipv6 .* rip send"
syn match	yamahaStatement		"^\s*ipv6 .* rip trust gateway"
syn match	yamahaStatement		"^\s*ipv6 .* rtadv send"
syn match	yamahaStatement		"^\s*ipv6 .* tcp mss limit"
syn match	yamahaStatement		"^\s*ipv6 .* vrrp"
syn match	yamahaStatement		"^\s*ipv6 .* vrrp shutdown trigger"
syn match	yamahaStatement		"^\s*ipv6 .* address"
syn match	yamahaStatement		"^\s*ipv6 .* dad retry count"
syn match	yamahaStatement		"^\s*ipv6 .* prefix"
syn match	yamahaStatement		"^\s*ipv6 .* prefix change log"
syn match	yamahaStatement		"^\s*ipv6 .* secure filter"
syn match	yamahaStatement		"^\s*isdn remote address call"
syn match	yamahaStatement		"^\s*isdn local address"
syn match	yamahaStatement		"^\s*l2tp always-on"
syn match	yamahaStatement		"^\s*l2tp hostname"
syn match	yamahaStatement		"^\s*l2tp keepalive log"
syn match	yamahaStatement		"^\s*l2tp keepalive use"
syn match	yamahaStatement		"^\s*l2tp local router-id"
syn match	yamahaStatement		"^\s*l2tp remote end-id"
syn match	yamahaStatement		"^\s*l2tp remote router-id"
syn match	yamahaStatement		"^\s*l2tp service"
syn match	yamahaStatement		"^\s*l2tp syslog"
syn match	yamahaStatement		"^\s*l2tp tunnel auth"
syn match	yamahaStatement		"^\s*l2tp tunnel disconnect time"
syn match	yamahaStatement		"^\s*lan backup recovery time"
syn match	yamahaStatement		"^\s*lan backup"
syn match	yamahaStatement		"^\s*lan count-hub-overflow"
syn match	yamahaStatement		"^\s*lan keepalive interval"
syn match	yamahaStatement		"^\s*lan keepalive log"
syn match	yamahaStatement		"^\s*lan keepalive use"
syn match	yamahaStatement		"^\s*lan linkup send-wait-time"
syn match	yamahaStatement		"^\s*lan port-mirroring lan1"
syn match	yamahaStatement		"^\s*lan shutdown"
syn match	yamahaStatement		"^\s*lan type"
syn match	yamahaStatement		"^\s*lan type lan[1-9] port-based-option"
syn match	yamahaStatement		"^\s*less"
syn match	yamahaStatement		"^\s*less config"
syn match	yamahaStatement		"^\s*less config list"
syn match	yamahaStatement		"^\s*less config pp"
syn match	yamahaStatement		"^\s*less config tunnel"
syn match	yamahaStatement		"^\s*less exec list"
syn match	yamahaStatement		"^\s*less file list"
syn match	yamahaStatement		"^\s*less log"
syn match	yamahaStatement		"^\s*line type"
syn match	yamahaStatement		"^\s*login password"
syn match	yamahaStatement		"^\s*login password encrypted"
syn match	yamahaStatement		"^\s*login radius use"
syn match	yamahaStatement		"^\s*login timer"
syn match	yamahaStatement		"^\s*login user"
syn match	yamahaStatement		"^\s*lua"
syn match	yamahaStatement		"^\s*lua use"
syn match	yamahaStatement		"^\s*luac"
syn match	yamahaStatement		"^\s*mail notify"
syn match	yamahaStatement		"^\s*mail notify status exec"
syn match	yamahaStatement		"^\s*mail server name"
syn match	yamahaStatement		"^\s*mail server pop"
syn match	yamahaStatement		"^\s*mail server smtp"
syn match	yamahaStatement		"^\s*mail server timeout"
syn match	yamahaStatement		"^\s*mail template"
syn match	yamahaStatement		"^\s*make directory"
syn match	yamahaStatement		"^\s*mobile access limit connection length"
syn match	yamahaStatement		"^\s*mobile access limit connection time"
syn match	yamahaStatement		"^\s*mobile access limit duration"
syn match	yamahaStatement		"^\s*mobile access limit length"
syn match	yamahaStatement		"^\s*mobile access limit time"
syn match	yamahaStatement		"^\s*mobile access-point name"
syn match	yamahaStatement		"^\s*mobile auto connect"
syn match	yamahaStatement		"^\s*mobile call prohibit auth-error count"
syn match	yamahaStatement		"^\s*mobile dial number"
syn match	yamahaStatement		"^\s*mobile disconnect input time"
syn match	yamahaStatement		"^\s*mobile disconnect output time"
syn match	yamahaStatement		"^\s*mobile disconnect time"
syn match	yamahaStatement		"^\s*mobile display caller id"
syn match	yamahaStatement		"^\s*mobile pin code usb1"
syn match	yamahaStatement		"^\s*mobile signal-strength"
syn match	yamahaStatement		"^\s*mobile signal-strength go"
syn match	yamahaStatement		"^\s*mobile syslog"
syn match	yamahaStatement		"^\s*mobile use"
syn match	yamahaStatement		"^\s*nat descriptor address inner"
syn match	yamahaStatement		"^\s*nat descriptor address outer"
syn match	yamahaStatement		"^\s*nat descriptor ftp port"
syn match	yamahaStatement		"^\s*nat descriptor log"
syn match	yamahaStatement		"^\s*nat descriptor masquerade incoming"
syn match	yamahaStatement		"^\s*nat descriptor masquerade port range"
syn match	yamahaStatement		"^\s*nat descriptor masquerade remove df-bit"
syn match	yamahaStatement		"^\s*nat descriptor masquerade rlogin"
syn match	yamahaStatement		"^\s*nat descriptor masquerade session limit"
syn match	yamahaStatement		"^\s*nat descriptor masquerade static"
syn match	yamahaStatement		"^\s*nat descriptor masquerade unconvertible port"
syn match	yamahaStatement		"^\s*nat descriptor sip"
syn match	yamahaStatement		"^\s*nat descriptor static"
syn match	yamahaStatement		"^\s*nat descriptor timer"
syn match	yamahaStatement		"^\s*nat descriptor type"
syn match	yamahaStatement		"^\s*netvolante-dns auto hostname pp"
syn match	yamahaStatement		"^\s*netvolante-dns auto hostname wan1"
syn match	yamahaStatement		"^\s*netvolante-dns auto hostname"
syn match	yamahaStatement		"^\s*netvolante-dns auto save"
syn match	yamahaStatement		"^\s*netvolante-dns delete go pp"
syn match	yamahaStatement		"^\s*netvolante-dns delete go wan1"
syn match	yamahaStatement		"^\s*netvolante-dns delete go"
syn match	yamahaStatement		"^\s*netvolante-dns get hostname list"
syn match	yamahaStatement		"^\s*netvolante-dns go pp"
syn match	yamahaStatement		"^\s*netvolante-dns go wan1"
syn match	yamahaStatement		"^\s*netvolante-dns go"
syn match	yamahaStatement		"^\s*netvolante-dns hostname host pp"
syn match	yamahaStatement		"^\s*netvolante-dns hostname host wan1"
syn match	yamahaStatement		"^\s*netvolante-dns hostname host"
syn match	yamahaStatement		"^\s*netvolante-dns port"
syn match	yamahaStatement		"^\s*netvolante-dns register timer"
syn match	yamahaStatement		"^\s*netvolante-dns retry interval pp"
syn match	yamahaStatement		"^\s*netvolante-dns retry interval wan1"
syn match	yamahaStatement		"^\s*netvolante-dns retry interval"
syn match	yamahaStatement		"^\s*netvolante-dns server"
syn match	yamahaStatement		"^\s*netvolante-dns server update address port"
syn match	yamahaStatement		"^\s*netvolante-dns server update address use"
syn match	yamahaStatement		"^\s*netvolante-dns set hostname pp"
syn match	yamahaStatement		"^\s*netvolante-dns set hostname wan1"
syn match	yamahaStatement		"^\s*netvolante-dns set hostname"
syn match	yamahaStatement		"^\s*netvolante-dns timeout pp"
syn match	yamahaStatement		"^\s*netvolante-dns timeout wan1"
syn match	yamahaStatement		"^\s*netvolante-dns timeout"
syn match	yamahaStatement		"^\s*netvolante-dns use pp"
syn match	yamahaStatement		"^\s*netvolante-dns use wan1"
syn match	yamahaStatement		"^\s*netvolante-dns use"
syn match	yamahaStatement		"^\s*ngn radius account callee"
syn match	yamahaStatement		"^\s*ngn radius account caller"
syn match	yamahaStatement		"^\s*ngn radius auth password"
syn match	yamahaStatement		"^\s*ngn type"
syn match	yamahaStatement		"^\s*nslookup"
syn match	yamahaStatement		"^\s*ntp backward-compatibility"
syn match	yamahaStatement		"^\s*ntp local address"
syn match	yamahaStatement		"^\s*ntpdate"
syn match	yamahaStatement		"^\s*operation button function download"
syn match	yamahaStatement		"^\s*operation execute batch permit"
syn match	yamahaStatement		"^\s*operation external-memory download permit"
syn match	yamahaStatement		"^\s*operation http revision-up permit"
syn match	yamahaStatement		"^\s*ospf area"
syn match	yamahaStatement		"^\s*ospf area network"
syn match	yamahaStatement		"^\s*ospf area stubhost"
syn match	yamahaStatement		"^\s*ospf configure refresh"
syn match	yamahaStatement		"^\s*ospf export filter"
syn match	yamahaStatement		"^\s*ospf export from"
syn match	yamahaStatement		"^\s*ospf import filter"
syn match	yamahaStatement		"^\s*ospf import from"
syn match	yamahaStatement		"^\s*ospf log"
syn match	yamahaStatement		"^\s*ospf merge equal cost stub"
syn match	yamahaStatement		"^\s*ospf preference"
syn match	yamahaStatement		"^\s*ospf router id"
syn match	yamahaStatement		"^\s*ospf use"
syn match	yamahaStatement		"^\s*ospf virtual-link"
syn match	yamahaStatement		"^\s*packetdump pp"
syn match	yamahaStatement		"^\s*packetdump wan1"
syn match	yamahaStatement		"^\s*packetdump"
syn match	yamahaStatement		"^\s*ping"
syn match	yamahaStatement		"^\s*ping6"
syn match	yamahaStatement		"^\s*pki certificate file"
syn match	yamahaStatement		"^\s*pki crl file"
syn match	yamahaStatement		"^\s*pp always-on"
syn match	yamahaStatement		"^\s*pp auth accept"
syn match	yamahaStatement		"^\s*pp auth multi connect prohibit"
syn match	yamahaStatement		"^\s*pp auth myname"
syn match	yamahaStatement		"^\s*pp auth request"
syn match	yamahaStatement		"^\s*pp auth username"
syn match	yamahaStatement		"^\s*pp backup"
syn match	yamahaStatement		"^\s*pp backup recovery time"
syn match	yamahaStatement		"^\s*pp bind"
syn match	yamahaStatement		"^\s*pp disable"
syn match	yamahaStatement		"^\s*pp enable"
syn match	yamahaStatement		"^\s*pp keepalive interval"
syn match	yamahaStatement		"^\s*pp keepalive log"
syn match	yamahaStatement		"^\s*pp keepalive use"
syn match	yamahaStatement		"^\s*pp name"
syn match	yamahaStatement		"^\s*pp select"
syn match	yamahaStatement		"^\s*ppp ccp maxconfigure"
syn match	yamahaStatement		"^\s*ppp ccp maxfailure"
syn match	yamahaStatement		"^\s*ppp ccp maxterminate"
syn match	yamahaStatement		"^\s*ppp ccp no-encryption"
syn match	yamahaStatement		"^\s*ppp ccp restart"
syn match	yamahaStatement		"^\s*ppp ccp type"
syn match	yamahaStatement		"^\s*ppp chap maxchallenge"
syn match	yamahaStatement		"^\s*ppp chap restart"
syn match	yamahaStatement		"^\s*ppp ipcp ipaddress"
syn match	yamahaStatement		"^\s*ppp ipcp maxconfigure"
syn match	yamahaStatement		"^\s*ppp ipcp maxfailure"
syn match	yamahaStatement		"^\s*ppp ipcp maxterminate"
syn match	yamahaStatement		"^\s*ppp ipcp msext"
syn match	yamahaStatement		"^\s*ppp ipcp remote address check"
syn match	yamahaStatement		"^\s*ppp ipcp restart"
syn match	yamahaStatement		"^\s*ppp ipcp vjc"
syn match	yamahaStatement		"^\s*ppp ipv6cp use"
syn match	yamahaStatement		"^\s*ppp lcp accm"
syn match	yamahaStatement		"^\s*ppp lcp acfc"
syn match	yamahaStatement		"^\s*ppp lcp magicnumber"
syn match	yamahaStatement		"^\s*ppp lcp maxconfigure"
syn match	yamahaStatement		"^\s*ppp lcp maxfailure"
syn match	yamahaStatement		"^\s*ppp lcp maxterminate"
syn match	yamahaStatement		"^\s*ppp lcp mru"
syn match	yamahaStatement		"^\s*ppp lcp pfc"
syn match	yamahaStatement		"^\s*ppp lcp restart"
syn match	yamahaStatement		"^\s*ppp lcp silent"
syn match	yamahaStatement		"^\s*ppp mscbcp maxretry"
syn match	yamahaStatement		"^\s*ppp mscbcp restart"
syn match	yamahaStatement		"^\s*ppp pap maxauthreq"
syn match	yamahaStatement		"^\s*ppp pap restart"
syn match	yamahaStatement		"^\s*pppoe access concentrator"
syn match	yamahaStatement		"^\s*pppoe auto connect"
syn match	yamahaStatement		"^\s*pppoe auto disconnect"
syn match	yamahaStatement		"^\s*pppoe call prohibit"
syn match	yamahaStatement		"^\s*pppoe disconnect time"
syn match	yamahaStatement		"^\s*pppoe invalid-session forced close"
syn match	yamahaStatement		"^\s*pppoe padi maxretry"
syn match	yamahaStatement		"^\s*pppoe padi restart"
syn match	yamahaStatement		"^\s*pppoe padr maxretry"
syn match	yamahaStatement		"^\s*pppoe padr restart"
syn match	yamahaStatement		"^\s*pppoe service-name"
syn match	yamahaStatement		"^\s*pppoe tcp mss limit"
syn match	yamahaStatement		"^\s*pppoe use"
syn match	yamahaStatement		"^\s*pptp hostname"
syn match	yamahaStatement		"^\s*pptp keepalive interval"
syn match	yamahaStatement		"^\s*pptp keepalive log"
syn match	yamahaStatement		"^\s*pptp keepalive use"
syn match	yamahaStatement		"^\s*pptp service"
syn match	yamahaStatement		"^\s*pptp service type"
syn match	yamahaStatement		"^\s*pptp syslog"
syn match	yamahaStatement		"^\s*pptp tunnel disconnect time"
syn match	yamahaStatement		"^\s*pptp window size"
syn match	yamahaStatement		"^\s*provider auto connect forced disable"
syn match	yamahaStatement		"^\s*provider dns server"
syn match	yamahaStatement		"^\s*provider dns server pp"
syn match	yamahaStatement		"^\s*provider filter routing"
syn match	yamahaStatement		"^\s*provider ipv6 connect pp"
syn match	yamahaStatement		"^\s*provider lan[1-9] name"
syn match	yamahaStatement		"^\s*provider ntp server"
syn match	yamahaStatement		"^\s*provider ntpdate"
syn match	yamahaStatement		"^\s*provider pp bind"
syn match	yamahaStatement		"^\s*provider select"
syn match	yamahaStatement		"^\s*provider set"
syn match	yamahaStatement		"^\s*provider type"
syn match	yamahaStatement		"^\s*provider wan1 bind"
syn match	yamahaStatement		"^\s*provider wan1 dns server"
syn match	yamahaStatement		"^\s*provider wan1 name"
syn match	yamahaStatement		"^\s*provider .* bind"
syn match	yamahaStatement		"^\s*provider .* dns server"
syn match	yamahaStatement		"^\s*provider .* name"
syn match	yamahaStatement		"^\s*queue class filter"
syn match	yamahaStatement		"^\s*queue pp class filter list"
syn match	yamahaStatement		"^\s*queue pp default class"
syn match	yamahaStatement		"^\s*queue pp length"
syn match	yamahaStatement		"^\s*queue pp type"
syn match	yamahaStatement		"^\s*queue tunnel class filter list"
syn match	yamahaStatement		"^\s*queue wan1 class control"
syn match	yamahaStatement		"^\s*queue wan1 class filter list"
syn match	yamahaStatement		"^\s*queue wan1 class property"
syn match	yamahaStatement		"^\s*queue wan1 default class"
syn match	yamahaStatement		"^\s*queue wan1 length"
syn match	yamahaStatement		"^\s*queue wan1 type"
syn match	yamahaStatement		"^\s*queue .* class control"
syn match	yamahaStatement		"^\s*queue .* class filter list"
syn match	yamahaStatement		"^\s*queue .* class property"
syn match	yamahaStatement		"^\s*queue .* default class"
syn match	yamahaStatement		"^\s*queue .* length"
syn match	yamahaStatement		"^\s*queue .* type"
syn match	yamahaStatement		"^\s*quit"
syn match	yamahaStatement		"^\s*radius account"
syn match	yamahaStatement		"^\s*radius account port"
syn match	yamahaStatement		"^\s*radius account server"
syn match	yamahaStatement		"^\s*radius auth"
syn match	yamahaStatement		"^\s*radius auth port"
syn match	yamahaStatement		"^\s*radius auth server"
syn match	yamahaStatement		"^\s*radius retry"
syn match	yamahaStatement		"^\s*radius secret"
syn match	yamahaStatement		"^\s*radius server"
syn match	yamahaStatement		"^\s*rdate"
syn match	yamahaStatement		"^\s*remote setup accept"
syn match	yamahaStatement		"^\s*rename"
syn match	yamahaStatement		"^\s*restart"
syn match	yamahaStatement		"^\s*rip filter rule"
syn match	yamahaStatement		"^\s*rip preference"
syn match	yamahaStatement		"^\s*rip timer"
syn match	yamahaStatement		"^\s*rip use"
syn match	yamahaStatement		"^\s*rotate external-memory syslog"
syn match	yamahaStatement		"^\s*rtfs format"
syn match	yamahaStatement		"^\s*rtfs garbage-collect"
syn match	yamahaStatement		"^\s*save"
syn match	yamahaStatement		"^\s*schedule at"
syn match	yamahaStatement		"^\s*scp"
syn match	yamahaStatement		"^\s*sd use"
syn match	yamahaStatement		"^\s*security class"
syn match	yamahaStatement		"^\s*set"
syn match	yamahaStatement		"^\s*set-default-config"
syn match	yamahaStatement		"^\s*sftpd host"
syn match	yamahaStatement		"^\s*show account"
syn match	yamahaStatement		"^\s*show account mobile"
syn match	yamahaStatement		"^\s*show account ngn data"
syn match	yamahaStatement		"^\s*show account pp"
syn match	yamahaStatement		"^\s*show arp"
syn match	yamahaStatement		"^\s*show bridge learning"
syn match	yamahaStatement		"^\s*show command"
syn match	yamahaStatement		"^\s*show config"
syn match	yamahaStatement		"^\s*show config list"
syn match	yamahaStatement		"^\s*show config pp"
syn match	yamahaStatement		"^\s*show config tunnel"
syn match	yamahaStatement		"^\s*show dns cache"
syn match	yamahaStatement		"^\s*show environment"
syn match	yamahaStatement		"^\s*show exec list"
syn match	yamahaStatement		"^\s*show file list"
syn match	yamahaStatement		"^\s*show history"
syn match	yamahaStatement		"^\s*show ip connection"
syn match	yamahaStatement		"^\s*show ip intrusion detection"
syn match	yamahaStatement		"^\s*show ip rip table"
syn match	yamahaStatement		"^\s*show ip route"
syn match	yamahaStatement		"^\s*show ip secure filter loopback1"
syn match	yamahaStatement		"^\s*show ip secure filter loopback2"
syn match	yamahaStatement		"^\s*show ip secure filter loopback3"
syn match	yamahaStatement		"^\s*show ip secure filter loopback4"
syn match	yamahaStatement		"^\s*show ip secure filter loopback5"
syn match	yamahaStatement		"^\s*show ip secure filter loopback6"
syn match	yamahaStatement		"^\s*show ip secure filter loopback7"
syn match	yamahaStatement		"^\s*show ip secure filter loopback8"
syn match	yamahaStatement		"^\s*show ip secure filter loopback9"
syn match	yamahaStatement		"^\s*show ip secure filter null"
syn match	yamahaStatement		"^\s*show ip secure filter pp"
syn match	yamahaStatement		"^\s*show ip secure filter tunnel"
syn match	yamahaStatement		"^\s*show ip secure filter wan1"
syn match	yamahaStatement		"^\s*show ip secure filter"
syn match	yamahaStatement		"^\s*show ipsec sa"
syn match	yamahaStatement		"^\s*show ipv6 address"
syn match	yamahaStatement		"^\s*show ipv6 connection"
syn match	yamahaStatement		"^\s*show ipv6 mroute fib"
syn match	yamahaStatement		"^\s*show ipv6 neighbor cache"
syn match	yamahaStatement		"^\s*show ipv6 ospf"
syn match	yamahaStatement		"^\s*show ipv6 rip table"
syn match	yamahaStatement		"^\s*show ipv6 route"
syn match	yamahaStatement		"^\s*show log"
syn match	yamahaStatement		"^\s*show nat descriptor address"
syn match	yamahaStatement		"^\s*show nat descriptor interface address pp"
syn match	yamahaStatement		"^\s*show nat descriptor interface address tunnel"
syn match	yamahaStatement		"^\s*show nat descriptor interface address wan1"
syn match	yamahaStatement		"^\s*show nat descriptor interface address"
syn match	yamahaStatement		"^\s*show nat descriptor interface bind pp"
syn match	yamahaStatement		"^\s*show nat descriptor interface bind tunnel"
syn match	yamahaStatement		"^\s*show nat descriptor interface bind wan1"
syn match	yamahaStatement		"^\s*show nat descriptor interface bind"
syn match	yamahaStatement		"^\s*show nat descriptor masquerade port"
syn match	yamahaStatement		"^\s*show pki certificate summary"
syn match	yamahaStatement		"^\s*show pki crl"
syn match	yamahaStatement		"^\s*show pp connect time"
syn match	yamahaStatement		"^\s*show sshd public key"
syn match	yamahaStatement		"^\s*show status backup"
syn match	yamahaStatement		"^\s*show status bgp"
syn match	yamahaStatement		"^\s*show status boot"
syn match	yamahaStatement		"^\s*show status boot all"
syn match	yamahaStatement		"^\s*show status boot list"
syn match	yamahaStatement		"^\s*show status cooperation"
syn match	yamahaStatement		"^\s*show status dhcp"
syn match	yamahaStatement		"^\s*show status dhcpc"
syn match	yamahaStatement		"^\s*show status ethernet"
syn match	yamahaStatement		"^\s*show status external-memory"
syn match	yamahaStatement		"^\s*show status heartbeat"
syn match	yamahaStatement		"^\s*show status heartbeat2"
syn match	yamahaStatement		"^\s*show status ip keepalive"
syn match	yamahaStatement		"^\s*show status ipv6 dhcp"
syn match	yamahaStatement		"^\s*show status ipv6 mld"
syn match	yamahaStatement		"^\s*show status l2tp"
syn match	yamahaStatement		"^\s*show status l2tp tunnel"
syn match	yamahaStatement		"^\s*show status lua"
syn match	yamahaStatement		"^\s*show status mail service"
syn match	yamahaStatement		"^\s*show status mobile signal-strength"
syn match	yamahaStatement		"^\s*show status netvolante-dns pp"
syn match	yamahaStatement		"^\s*show status netvolante-dns wan1"
syn match	yamahaStatement		"^\s*show status netvolante-dns"
syn match	yamahaStatement		"^\s*show status ngn"
syn match	yamahaStatement		"^\s*show status ospf"
syn match	yamahaStatement		"^\s*show status packet-buffer"
syn match	yamahaStatement		"^\s*show status pp"
syn match	yamahaStatement		"^\s*show status pptp"
syn match	yamahaStatement		"^\s*show status qos"
syn match	yamahaStatement		"^\s*show status remote setup"
syn match	yamahaStatement		"^\s*show status rtfs"
syn match	yamahaStatement		"^\s*show status sd"
syn match	yamahaStatement		"^\s*show status switch control"
syn match	yamahaStatement		"^\s*show status switch control route backup"
syn match	yamahaStatement		"^\s*show status switching-hub macaddress"
syn match	yamahaStatement		"^\s*show status tunnel"
syn match	yamahaStatement		"^\s*show status upnp"
syn match	yamahaStatement		"^\s*show status usbhost"
syn match	yamahaStatement		"^\s*show status usbhost modem"
syn match	yamahaStatement		"^\s*show status user"
syn match	yamahaStatement		"^\s*show status vlan"
syn match	yamahaStatement		"^\s*show status vrrp"
syn match	yamahaStatement		"^\s*show status wan1"
syn match	yamahaStatement		"^\s*show status"
syn match	yamahaStatement		"^\s*show techinfo"
syn match	yamahaStatement		"^\s*show url filter"
syn match	yamahaStatement		"^\s*sip 100rel"
syn match	yamahaStatement		"^\s*sip arrive address check"
syn match	yamahaStatement		"^\s*sip arrive ringing p-n-uatype"
syn match	yamahaStatement		"^\s*sip arrive session timer method"
syn match	yamahaStatement		"^\s*sip arrive session timer refresher"
syn match	yamahaStatement		"^\s*sip codec permit"
syn match	yamahaStatement		"^\s*sip ip protocol"
syn match	yamahaStatement		"^\s*sip log"
syn match	yamahaStatement		"^\s*sip outer address"
syn match	yamahaStatement		"^\s*sip response code busy"
syn match	yamahaStatement		"^\s*sip session timer"
syn match	yamahaStatement		"^\s*sip use"
syn match	yamahaStatement		"^\s*sip user agent"
syn match	yamahaStatement		"^\s*snmp community read-only"
syn match	yamahaStatement		"^\s*snmp community read-write"
syn match	yamahaStatement		"^\s*snmp display ipcp force"
syn match	yamahaStatement		"^\s*snmp host"
syn match	yamahaStatement		"^\s*snmp ifindex switch static index"
syn match	yamahaStatement		"^\s*snmp local address"
syn match	yamahaStatement		"^\s*snmp syscontact"
syn match	yamahaStatement		"^\s*snmp syslocation"
syn match	yamahaStatement		"^\s*snmp sysname"
syn match	yamahaStatement		"^\s*snmp trap community"
syn match	yamahaStatement		"^\s*snmp trap enable snmp"
syn match	yamahaStatement		"^\s*snmp trap enable switch"
syn match	yamahaStatement		"^\s*snmp trap enable switch common"
syn match	yamahaStatement		"^\s*snmp trap host"
syn match	yamahaStatement		"^\s*snmp trap link-updown separate-l2switch-port lan1"
syn match	yamahaStatement		"^\s*snmp trap mobile signal-strength"
syn match	yamahaStatement		"^\s*snmp trap send linkdown pp"
syn match	yamahaStatement		"^\s*snmp trap send linkdown tunnel"
syn match	yamahaStatement		"^\s*snmp trap send linkdown wan1"
syn match	yamahaStatement		"^\s*snmp trap send linkdown"
syn match	yamahaStatement		"^\s*snmp yrifppdisplayatmib2"
syn match	yamahaStatement		"^\s*snmp yrifswitchdisplayatmib2"
syn match	yamahaStatement		"^\s*snmp yriftunneldisplayatmib2"
syn match	yamahaStatement		"^\s*snmp yrswindex switch static index"
syn match	yamahaStatement		"^\s*snmpv2c community read-only"
syn match	yamahaStatement		"^\s*snmpv2c community read-write"
syn match	yamahaStatement		"^\s*snmpv2c host"
syn match	yamahaStatement		"^\s*snmpv2c trap community"
syn match	yamahaStatement		"^\s*snmpv2c trap host"
syn match	yamahaStatement		"^\s*snmpv3 context name"
syn match	yamahaStatement		"^\s*snmpv3 engine id"
syn match	yamahaStatement		"^\s*snmpv3 host"
syn match	yamahaStatement		"^\s*snmpv3 trap host"
syn match	yamahaStatement		"^\s*snmpv3 usm user"
syn match	yamahaStatement		"^\s*snmpv3 vacm access"
syn match	yamahaStatement		"^\s*snmpv3 vacm view"
syn match	yamahaStatement		"^\s*sntpd host"
syn match	yamahaStatement		"^\s*sntpd service"
syn match	yamahaStatement		"^\s*speed wan1"
syn match	yamahaStatement		"^\s*speed"
syn match	yamahaStatement		"^\s*ssh"
syn match	yamahaStatement		"^\s*ssh encrypt algorithm"
syn match	yamahaStatement		"^\s*ssh known hosts"
syn match	yamahaStatement		"^\s*sshd client alive"
syn match	yamahaStatement		"^\s*sshd encrypt algorithm"
syn match	yamahaStatement		"^\s*sshd host"
syn match	yamahaStatement		"^\s*sshd host key generate"
syn match	yamahaStatement		"^\s*sshd listen"
syn match	yamahaStatement		"^\s*sshd service"
syn match	yamahaStatement		"^\s*sshd session"
syn match	yamahaStatement		"^\s*statistics cpu"
syn match	yamahaStatement		"^\s*statistics memory"
syn match	yamahaStatement		"^\s*switch control firmware upload go"
syn match	yamahaStatement		"^\s*switch control function default"
syn match	yamahaStatement		"^\s*switch control function execute clear-counter"
syn match	yamahaStatement		"^\s*switch control function execute clear-macaddress-table"
syn match	yamahaStatement		"^\s*switch control function execute reset-loopdetect"
syn match	yamahaStatement		"^\s*switch control function execute restart"
syn match	yamahaStatement		"^\s*switch control function execute restart-poe-supply"
syn match	yamahaStatement		"^\s*switch control function get boot-rom-version"
syn match	yamahaStatement		"^\s*switch control function get counter-frame-rx-type"
syn match	yamahaStatement		"^\s*switch control function get counter-frame-tx-type"
syn match	yamahaStatement		"^\s*switch control function get energy-saving"
syn match	yamahaStatement		"^\s*switch control function get firmware-revision"
syn match	yamahaStatement		"^\s*switch control function get led-brightness"
syn match	yamahaStatement		"^\s*switch control function get loopdetect-count"
syn match	yamahaStatement		"^\s*switch control function get loopdetect-linkdown"
syn match	yamahaStatement		"^\s*switch control function get loopdetect-port-use"
syn match	yamahaStatement		"^\s*switch control function get loopdetect-recovery-timer"
syn match	yamahaStatement		"^\s*switch control function get loopdetect-time"
syn match	yamahaStatement		"^\s*switch control function get loopdetect-use-control-packet"
syn match	yamahaStatement		"^\s*loopdetect-use-control-packetの設定値を取得します"
syn match	yamahaStatement		"^\s*switch control function get macaddress-aging"
syn match	yamahaStatement		"^\s*switch control function get macaddress-aging-timer"
syn match	yamahaStatement		"^\s*switch control function get mirroring-dest"
syn match	yamahaStatement		"^\s*switch control function get mirroring-src-rx"
syn match	yamahaStatement		"^\s*switch control function get mirroring-src-tx"
syn match	yamahaStatement		"^\s*switch control function get mirroring-use"
syn match	yamahaStatement		"^\s*switch control function get model-name"
syn match	yamahaStatement		"^\s*switch control function get poe-class"
syn match	yamahaStatement		"^\s*switch control function get port-auto-crossover"
syn match	yamahaStatement		"^\s*switch control function get port-blocking-control-packet"
syn match	yamahaStatement		"^\s*switch control function get port-blocking-data-packet"
syn match	yamahaStatement		"^\s*switch control function get port-flow-control"
syn match	yamahaStatement		"^\s*switch control function get port-speed"
syn match	yamahaStatement		"^\s*switch control function get port-speed-downshift"
syn match	yamahaStatement		"^\s*switch control function get port-use"
syn match	yamahaStatement		"^\s*switch control function get qos-dscp-remark-class"
syn match	yamahaStatement		"^\s*switch control function get qos-dscp-remark-type"
syn match	yamahaStatement		"^\s*switch control function get qos-policing-speed"
syn match	yamahaStatement		"^\s*switch control function get qos-policing-use"
syn match	yamahaStatement		"^\s*switch control function get qos-shaping-speed"
syn match	yamahaStatement		"^\s*switch control function get qos-shaping-use"
syn match	yamahaStatement		"^\s*switch control function get qos-speed-unit"
syn match	yamahaStatement		"^\s*switch control function get serial-number"
syn match	yamahaStatement		"^\s*switch control function get status-counter-frame-rx"
syn match	yamahaStatement		"^\s*switch control function get status-counter-frame-tx"
syn match	yamahaStatement		"^\s*switch control function get status-counter-octet-rx"
syn match	yamahaStatement		"^\s*switch control function get status-counter-octet-tx"
syn match	yamahaStatement		"^\s*switch control function get status-fan"
syn match	yamahaStatement		"^\s*switch control function get status-fan-rpm"
syn match	yamahaStatement		"^\s*switch control function get status-led-mode"
syn match	yamahaStatement		"^\s*switch control function get status-loopdetect-port"
syn match	yamahaStatement		"^\s*switch control function get status-loopdetect-recovery-timer"
syn match	yamahaStatement		"^\s*switch control function get status-macaddress-addr"
syn match	yamahaStatement		"^\s*switch control function get status-macaddress-port"
syn match	yamahaStatement		"^\s*switch control function get status-poe-detect-class"
syn match	yamahaStatement		"^\s*switch control function get status-poe-state"
syn match	yamahaStatement		"^\s*switch control function get status-poe-supply"
syn match	yamahaStatement		"^\s*switch control function get status-poe-temperature"
syn match	yamahaStatement		"^\s*switch control function get status-port-speed"
syn match	yamahaStatement		"^\s*switch control function get system-macaddress"
syn match	yamahaStatement		"^\s*switch control function get system-name"
syn match	yamahaStatement		"^\s*switch control function get system-uptime"
syn match	yamahaStatement		"^\s*switch control function get vlan-access"
syn match	yamahaStatement		"^\s*switch control function get vlan-id"
syn match	yamahaStatement		"^\s*switch control function get vlan-multiple"
syn match	yamahaStatement		"^\s*switch control function get vlan-multiple-use"
syn match	yamahaStatement		"^\s*switch control function get vlan-port-mode"
syn match	yamahaStatement		"^\s*switch control function get vlan-trunk"
syn match	yamahaStatement		"^\s*switch control function set counter-frame-rx-type"
syn match	yamahaStatement		"^\s*switch control function set counter-frame-tx-type"
syn match	yamahaStatement		"^\s*switch control function set energy-saving"
syn match	yamahaStatement		"^\s*switch control function set led-brightness"
syn match	yamahaStatement		"^\s*switch control function set loopdetect-count"
syn match	yamahaStatement		"^\s*switch control function set loopdetect-linkdown"
syn match	yamahaStatement		"^\s*switch control function set loopdetect-port-use"
syn match	yamahaStatement		"^\s*switch control function set loopdetect-recovery-timer"
syn match	yamahaStatement		"^\s*switch control function set loopdetect-time"
syn match	yamahaStatement		"^\s*switch control function set loopdetect-use-control-packet"
syn match	yamahaStatement		"^\s*switch control function set macaddress-aging"
syn match	yamahaStatement		"^\s*switch control function set macaddress-aging-timer"
syn match	yamahaStatement		"^\s*switch control function set mirroring-dest"
syn match	yamahaStatement		"^\s*switch control function set mirroring-src-rx"
syn match	yamahaStatement		"^\s*switch control function set mirroring-src-tx"
syn match	yamahaStatement		"^\s*switch control function set mirroring-use"
syn match	yamahaStatement		"^\s*switch control function set poe-class"
syn match	yamahaStatement		"^\s*switch control function set port-auto-crossover"
syn match	yamahaStatement		"^\s*switch control function set port-blocking-control-packet"
syn match	yamahaStatement		"^\s*switch control function set port-blocking-data-packet"
syn match	yamahaStatement		"^\s*switch control function set port-flow-control"
syn match	yamahaStatement		"^\s*switch control function set port-speed"
syn match	yamahaStatement		"^\s*switch control function set port-speed-downshift"
syn match	yamahaStatement		"^\s*switch control function set port-use"
syn match	yamahaStatement		"^\s*switch control function set qos-dscp-remark-class"
syn match	yamahaStatement		"^\s*switch control function set qos-dscp-remark-type"
syn match	yamahaStatement		"^\s*switch control function set qos-policing-speed"
syn match	yamahaStatement		"^\s*switch control function set qos-policing-use"
syn match	yamahaStatement		"^\s*switch control function set qos-shaping-speed"
syn match	yamahaStatement		"^\s*switch control function set qos-shaping-use"
syn match	yamahaStatement		"^\s*switch control function set qos-speed-unit"
syn match	yamahaStatement		"^\s*switch control function set system-name"
syn match	yamahaStatement		"^\s*switch control function set vlan-access"
syn match	yamahaStatement		"^\s*switch control function set vlan-id"
syn match	yamahaStatement		"^\s*switch control function set vlan-multiple"
syn match	yamahaStatement		"^\s*switch control function set vlan-multiple-use"
syn match	yamahaStatement		"^\s*switch control function set vlan-port-mode"
syn match	yamahaStatement		"^\s*switch control function set vlan-trunk"
syn match	yamahaStatement		"^\s*switch control route backup"
syn match	yamahaStatement		"^\s*switch control use"
syn match	yamahaStatement		"^\s*switch control watch interval"
syn match	yamahaStatement		"^\s*switch select"
syn match	yamahaStatement		"^\s*syslog debug"
syn match	yamahaStatement		"^\s*syslog execute command"
syn match	yamahaStatement		"^\s*syslog facility"
syn match	yamahaStatement		"^\s*syslog host"
syn match	yamahaStatement		"^\s*syslog info"
syn match	yamahaStatement		"^\s*syslog local address"
syn match	yamahaStatement		"^\s*syslog notice"
syn match	yamahaStatement		"^\s*syslog srcport"
syn match	yamahaStatement		"^\s*system led brightness"
syn match	yamahaStatement		"^\s*system packet-buffer"
syn match	yamahaStatement		"^\s*tcp log"
syn match	yamahaStatement		"^\s*tcp session limit"
syn match	yamahaStatement		"^\s*telnet"
syn match	yamahaStatement		"^\s*telnetd host"
syn match	yamahaStatement		"^\s*telnetd listen"
syn match	yamahaStatement		"^\s*telnetd service"
syn match	yamahaStatement		"^\s*telnetd session"
syn match	yamahaStatement		"^\s*terminate lua"
syn match	yamahaStatement		"^\s*terminate lua file"
syn match	yamahaStatement		"^\s*tftp host"
syn match	yamahaStatement		"^\s*time"
syn match	yamahaStatement		"^\s*timezone"
syn match	yamahaStatement		"^\s*traceroute"
syn match	yamahaStatement		"^\s*traceroute6"
syn match	yamahaStatement		"^\s*tunnel backup"
syn match	yamahaStatement		"^\s*tunnel disable"
syn match	yamahaStatement		"^\s*tunnel enable"
syn match	yamahaStatement		"^\s*tunnel encapsulation"
syn match	yamahaStatement		"^\s*tunnel endpoint address"
syn match	yamahaStatement		"^\s*tunnel endpoint name"
syn match	yamahaStatement		"^\s*tunnel name"
syn match	yamahaStatement		"^\s*tunnel ngn arrive permit"
syn match	yamahaStatement		"^\s*tunnel ngn bandwidth"
syn match	yamahaStatement		"^\s*tunnel ngn call permit"
syn match	yamahaStatement		"^\s*tunnel ngn disconnect time"
syn match	yamahaStatement		"^\s*tunnel ngn fallback"
syn match	yamahaStatement		"^\s*tunnel ngn interface"
syn match	yamahaStatement		"^\s*tunnel ngn radius auth"
syn match	yamahaStatement		"^\s*tunnel select"
syn match	yamahaStatement		"^\s*tunnel template"
syn match	yamahaStatement		"^\s*upnp external address refer"
syn match	yamahaStatement		"^\s*upnp port mapping timer"
syn match	yamahaStatement		"^\s*upnp port mapping timer type"
syn match	yamahaStatement		"^\s*upnp syslog"
syn match	yamahaStatement		"^\s*upnp use"
syn match	yamahaStatement		"^\s*url filter"
syn match	yamahaStatement		"^\s*url filter log"
syn match	yamahaStatement		"^\s*url filter port"
syn match	yamahaStatement		"^\s*url filter reject"
syn match	yamahaStatement		"^\s*url filter use"
syn match	yamahaStatement		"^\s*url pp filter"
syn match	yamahaStatement		"^\s*url tunnel filter"
syn match	yamahaStatement		"^\s*url wan1 filter"
syn match	yamahaStatement		"^\s*url .* filter"
syn match	yamahaStatement		"^\s*usbhost modem flow control"
syn match	yamahaStatement		"^\s*usbhost modem initialize"
syn match	yamahaStatement		"^\s*usbhost overcurrent duration"
syn match	yamahaStatement		"^\s*usbhost use"
syn match	yamahaStatement		"^\s*user attribute"
syn match	yamahaStatement		"^\s*vlan port mapping"
syn match	yamahaStatement		"^\s*vlan .* 802.1q"
syn match	yamahaStatement		"^\s*wan1 access limit connection length"
syn match	yamahaStatement		"^\s*wan1 access limit connection time"
syn match	yamahaStatement		"^\s*wan1 access limit duration"
syn match	yamahaStatement		"^\s*wan1 access limit length"
syn match	yamahaStatement		"^\s*wan1 access limit time"
syn match	yamahaStatement		"^\s*wan1 access-point name"
syn match	yamahaStatement		"^\s*wan1 always-on"
syn match	yamahaStatement		"^\s*wan1 auth myname"
syn match	yamahaStatement		"^\s*wan1 auto connect"
syn match	yamahaStatement		"^\s*wan1 bind"
syn match	yamahaStatement		"^\s*wan1 disconnect input time"
syn match	yamahaStatement		"^\s*wan1 disconnect output time"
syn match	yamahaStatement		"^\s*wan1 disconnect time"
syn match	yamahaStatement		"^\s*wins server"
syn match	yamahaStatement		"^\s*wol send"




hi link yamahaNumber	Number
hi link yamahaTime		Number
hi link yamahaString	String
hi link yamahaIPv4		Number
hi link yamahaSubnet	Number
hi link yamahaEmail		String
hi link yamahaURL		String
hi link yamahaBind		Number
hi link yamahaTunnel	Function
hi link yamahaVlan		Function
hi link yamahaPP		Function
hi link yamahaBRI		Function
hi link yamahaPRI		Function
hi link yamahaBridge	Function
hi link yamahaComment	Comment
hi link yamahaStatement	Statement
hi link yamahaEqual		Statement
hi link yamahaBuiltin	Function
hi link yamahaSplitinto	Function
hi link yamahaPort		Function
hi link yamahaBandwidth	Number
